version: "2"

services:
  map:
    image: map:latest
    build: .
    container_name: map
    expose: [3000]
    restart: unless-stopped
    environment:
      NS_API_KEY:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.map.rule=(Host(``))"
      - "traefik.http.routers.map.entrypoints=websecure"
      - "traefik.http.routers.map.tls.certresolver=myresolver"
